---
apiVersion: v2
name: bytebase
description: Bytebase is a Database CI/CD solution for the Developers and DBAs.
type: application
version: 1.0.2
appVersion: "3.4.1"
sources:
  - https://www.bytebase.com/
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
