---
apiVersion: v2
name: unifi-os-server
description: Ubiquiti UniFi network and device control platform
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/lemker/unifi-os-server/
dependencies:
  - name: common
    repository: oci://tccr.io/truecharts
    version: 28.23.0