---
apiVersion: v2
name: unifi-os-server
description: Ubiquiti UniFi network and device control platform
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/lemker/unifi-os-server/
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []