image:
  repository: ghcr.io/lemker/unifi-os-server
  pullPolicy: IfNotPresent
  tag: v1.0

securityContext:
  main:
    privileged: true

service:
  main:
    ports:
      main:
        protocol: https
        targetPort: 443
        port: 443
      rtp:
        protocol: tcp
        targetPort: 5005
        port: 5005
      id-hub:
        protocol: http
        targetPort: 9543
        port: 9543
      speedtest:
        protocol: http
        port: 6789
        targetPort: 6789
      communication:
        protocol: http
        port: 8080
        targetPort: 8080
      network-app:
        protocol: https
        port: 8443
        targetPort: 8443
      hotspot-secured:
        protocol: http
        port: 8444
        targetPort: 8444
      stun:
        protocol: udp
        port: 3478
        targetPort: 3478
      syslog:
        protocol: udp
        port: 5514
        targetPort: 5514
      discovery:
        protocol: udp
        port: 10003
        targetPort: 10003
      supervisor:
        protocol: tcp
        port: 11084
        targetPort: 11084
      aqmps:
        protocol: tcp
        port: 5671
        targetPort: 5671
      hotspot-redirect:
        protocol: http
        port: 8880
        targetPort: 8880
      hotspot-redirect-2:
        protocol: http
        port: 8882
        targetPort: 8882

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              type: http
              path: /api/ping
              port: 80
            readiness:
              type: http
              path: /api/ping
              port: 80
            startup:
              type: http
              path: /api/ping
              port: 80
          env:
            UOS_SYSTEM_IP: "{{ .Values.unifi.systemIp | required 'unifi.systemIp is required' }}"
persistence:
  data:
    mountPath: /data
    enabled: true
    readOnly: false
    type: emptyDir
  persistent:
    mountPath: /persistent
    enabled: true
    readOnly: false
    type: emptyDir
  varlog:
    mountPath: /var/log
    enabled: true
    readOnly: false
    type: emptyDir
  unifi:
    mountPath: /var/lib/unifi
    enabled: true
    readOnly: false
    type: emptyDir
  srv:
    mountPath: /srv
    enabled: true
    readOnly: false
    type: emptyDir
  mongodb:
    mountPath: /var/lib/mongodb
    enabled: true
    readOnly: false
    type: emptyDir
  rabbitmq-cert:
    mountPath: /etc/rabbitmq/ssl
    enabled: true
    readOnly: false
    type: emptyDir