apiVersion: v2
appVersion: "3.0.10.156"
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
home: https://foundryvtt.com/
icon: https://avatars.githubusercontent.com/u/106610688
keywords:
  - game
  - server
  - vtt
  - virtualtabletop
  - foundryvtt
  - foundry
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: spiegela@gmail.com
    name: Aaron Spiegel
name: foundry-vtt
description: Foundry Virtual Tabletop
sources:
  - https://github.com/hugoprudente/charts/tree/main/incubator/foundry-vtt
type: application
version: 0.0.3