image:
  repository: ghcr.io/booklore-app/booklore
  pullPolicy: IfNotPresent
  tag: v1.1.1@sha256:50a21ed8217bbf92cbf5ec259f52535754523d1541ae28cabd5d9ce037d1b453

securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 6060
        port: 6060

workload:
  main:
    podSpec:
      initContainers:
        init-db:
          type: install
          enabled: true
          imageSelector: "image"
          command:
            - /bin/ash
          args:
            - -c
            - mkdir /run/nginx
      containers:
        main:
          probes:
            liveness:
              type: tcp
            readiness:
              type: tcp
            startup:
              type: tcp
          env:
            DATABASE_URL:
              secretKeyRef:
                expandObjectName: false
                name: '{{ printf "%s-%s" .Release.Name "mariadbcreds" }}'
                key: jdbc-mariadb
            DATABASE_USERNAME: "{{ .Values.mariadb.mariadbUsername }}"
            DATABASE_PASSWORD: "{{ .Values.mariadb.password }}"
            BOOKLORE_PORT: "{{ .Values.service.main.ports.main.targetPort }}"
            SWAGGER_ENABLED: "true"
persistence:
  run:
    enabled: true
    mountPath: /run
    readOnly: false
    type: emptyDir
  config:
    enabled: true
    mountPath: /app/data
    readOnly: false
  books:
    enabled: true
    mountPath: /books
    readOnly: false
  magazines:
    enabled: true
    mountPath: /magazines
    readOnly: false
  bookdrop:
    enabled: true
    mountPath: /bookdrop
    readOnly: false

mariadb:
  enabled: true
  mariadbUsername: booklore
  mariadbDatabase: booklore