image:
  # -- image repository
  repository: ghcr.io/mrprimate/ddb-proxy
  # -- image tag
  tag: latest
  # -- image pull policy
  pullPolicy: IfNotPresent

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      main:
        port: 3000

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: /ping
            readiness:
              path: /ping
            startup:
              path: /ping
