---
apiVersion: v2
name: tubearchivist
description: Tube Archivist indexes, downloads, and serves a self-hosted YouTube media archive.
type: application
version: 1.0.0
appVersion: "latest"
sources:
  - https://github.com/tubearchivist/tubearchivist
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: [ ]
    import-values: [ ]
  - name: redis
    version: 17.9.1
    repository: oci://oci.trueforge.org/truecharts
    condition: redis.enabled
