image:
  repository: ghcr.io/music-assistant/server
  tag: "2.10.1"
  pullPolicy: IfNotPresent

alexaSkill:
  repository: ghcr.io/alams154/music-assistant-skill
  tag: 0.0.39-beta
  pullPolicy: IfNotPresent

config:
  server:
    hostname:
    url:
    apiToken:
  alexaSkill:
    url:
    username:
    password:
    enableAPL: false

workload:
  main:
    podSpec:
      containers:
        main:
          args:
            - --data-dir
            - /data
            - --cache-dir
            - /data/.cache
          env:
            APPDATA: /data
        alexa-skill:
          enabled: true
          primary: false
          imageSelector: alexaSkill
          env:
            SKILL_HOSTNAME: '{{ .Values.config.alexaSkill.url }}'
            MA_HOSTNAME: '{{ .Values.config.server.url }}'
            MA_API_TOKEN: '{{ .Values.config.server.apiToken }}'
            APP_USERNAME: /run/secrets/APP_USERNAME
            APP_PASSWORD: /run/secrets/APP_PASSWORD
            PORT: '{{ (index .Values.service.main.ports "alexa-skill").targetPort | default (index .Values.service.main.ports "alexa-skill").port }}'
            DEBUG_PORT: '{{ (index .Values.service.main.ports "alexa-debug").targetPort | default (index .Values.service.main.ports "alexa-debug").port }}'
            LOCALE: en-US # optional: skill locale (e.g. en-US, en-GB, de-DE)
            AWS_DEFAULT_REGION: us-east-1 #optional
          probes:
            liveness:
              enabled: true
              type: '{{ (index .Values.service.main.ports "alexa-skill").protocol }}'
              port: '{{ (index .Values.service.main.ports "alexa-skill").targetPort | default (index .Values.service.main.ports "alexa-skill").port }}'
            readiness:
              enabled: true
              type: '{{ (index .Values.service.main.ports "alexa-skill").protocol }}'
              port: '{{ (index .Values.service.main.ports "alexa-skill").targetPort | default (index .Values.service.main.ports "alexa-skill").port }}'
            startup:
              enabled: true
              type: '{{ (index .Values.service.main.ports "alexa-skill").protocol }}'
              port: '{{ (index .Values.service.main.ports "alexa-skill").targetPort | default (index .Values.service.main.ports "alexa-skill").port }}'

service:
  main:
    ports:
      main:
        enabled: true
        primary: true
        protocol: http
        port: 8095
        targetPort: 8095
      stream:
        enabled: true
        primary: false
        protocol: http
        port: 8097
        targetPort: 8097
      alexa-skill:
        enabled: true
        port: 5000
        targetPort: 5000
        protocol: tcp
      alexa-debug:
        enabled: true
        port: 5678
        targetPort: 5678
        protocol: tcp
      bonjour:
        enabled: true
        port: 5353
        targetPort: 5353
        protocol: tcp
      rtsp:
        enabled: true
        port: 554
        targetPort: 554
        protocol: tcp
      chromecast:
        enabled: true
        port: 8008
        targetPort: 8008
        protocol: tcp

securityContext:
  container:
    capabilities:
      add:
        - SYS_ADMIN
        - DAC_READ_SEARCH

secret:
  main:
    enabled: true
    data:
      APP_USERNAME : '{{ .Values.config.alexaSkill.username }}'
      APP_PASSWORD: '{{ .Values.config.alexaSkill.password }}'

persistence:
  secrets:
    enabled: true
    mountPath: "/run/secrets"
  alexa-skill-ask-data:
    enabled: true
    mountPath: /data/root/.ask
    readOnly: false
  data:
    enabled: true
    mountPath: /data
    readOnly: false
