---
apiVersion: v2
name: metamagic
description: MetaMagic is a Plex collections, artwork, overlays, and metadata manager with a web UI.
type: application
version: 1.0.0
appVersion: "latest"
sources:
  - https://github.com/drxen00/metamagic
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
