apiVersion: v2
appVersion: "2.2.1"
deprecated: false
home: https://github.com/ehough/docker-nfs-server
keywords:
  - nfs
  - file-sharing
kubeVersion: ">=1.16.0-0"
name: nfs-server
description: NFS Server
sources: []
type: application
version: 0.0.3

maintainers:
  - email: spiegela@gmail.com
    name: Aaron Spiegel

dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
