{{/*
  This helper constructs the data for our main Secret by looping over
  .Values.accounts and .Values.shares, generating environment variables
  that Samba will read. Then we pass that data to the built-in TrueCharts
  secret creation function `tc.v1.common.class.secret`.
*/}}

{{- define "samba.sambaSecretData" -}}
{{- $out := dict -}}

{{- range .Values.accounts }}
{{- $key := printf "ACCOUNT_%s" (upper .username) -}}
{{- $_ := set $out $key .password -}}
{{- end }}

{{/* 2) Convert each share into SAMBA_VOLUME_CONFIG_<SHARE> with semicolon-joined configLines */}}
{{- range .Values.shares }}
{{- $key := printf "SAMBA_VOLUME_CONFIG_%s" (upper .name) -}}
{{- $val := join "; " .configLines -}}
{{- $_ := set $out $key $val -}}
{{- end }}

{{/* 3) Optional global stanza lines -> SAMBA_GLOBAL_STANZA */}}
{{- if .Values.samba.globalStanzaLines }}
{{- $stanzaVal := join .Values.samba.globalStanzaLines "; " -}}
{{- $_ := set $out "SAMBA_GLOBAL_STANZA" $stanzaVal -}}
{{- end }}

{{/* 4) Additional Samba environment variables for global config (mapToGuest, logLevel) */}}
{{- if .Values.samba.mapToGuest }}
{{- $_ := set $out "SAMBA_CONF_MAP_TO_GUEST" .Values.samba.mapToGuest -}}
{{- end }}

{{- if .Values.samba.logLevel }}
{{- $_ := set $out "SAMBA_CONF_LOG_LEVEL" .Values.samba.logLevel -}}
{{- end }}

{{ $out | toYaml }}
{{- end }}