{{/* Make sure all variables are set properly */}}
{{- include "tc.v1.common.loader.init" . }}

{{- $_ := set .Values.secret.main "data" (include "samba.sambaSecretData" . | fromYaml ) -}}

{{/* Render the templates */}}
{{ include "tc.v1.common.loader.apply" . }}