---
apiVersion: v2
name: zotify
description: Zotify is a command-line Spotify music and podcast downloader, packaged here as a scheduled CronJob.
type: application
version: 1.0.0
appVersion: "latest"
sources:
  - https://github.com/zotify-dev/zotify
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: [ ]
    import-values: [ ]
