apiVersion: v2
appVersion: "3.0.10.156"
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
deprecated: false
home: https://github.com/jertel/vuegraf
icon: https://avatars.githubusercontent.com/u/106610688
keywords:
  - home-automation
  - vuegraf
  - vue
  - influxdb
kubeVersion: ">=1.16.0-0"
maintainers:
  - email: spiegela@gmail.com
    name: Aaron Spiegel
name: Vuegraf
description: Emporia Vue InfluxDB Integration
sources:
  - https://github.com/jertel/vuegraf
type: application
version: 0.0.2
