{{- if and (not .Values.existingSecret) (or .Values.secretEnv.SENDGRID_API_KEY .Values.secretEnv.CLOUDFLARE_ACCOUNT_ID .Values.secretEnv.CLOUDFLARE_API_TOKEN) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grove-kc.secretName" . }}
  labels:
    {{- include "grove-kc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $name, $value := .Values.secretEnv }}
  {{- if $value }}
  {{ $name }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
