---
apiVersion: v2
name: storyteller
description: Storyteller is a self-hosted platform for creating and reading ebooks with synced narration.
type: application
version: 1.0.0
appVersion: "latest"
sources:
  - https://github.com/smoores-dev/storyteller
  - https://gitlab.com/storyteller-platform/storyteller
dependencies:
  - name: common
    version: 28.29.17
    repository: oci://oci.trueforge.org/truecharts
    condition: ""
    alias: ""
    tags: []
    import-values: []
