image:
  repository: spiegela/comic-utils
  tag: v4.12.1
  pullPolicy: Always

service:
  main:
    ports:
      main:
        port: 5577

persistence:
  comics:
    enabled: true
    mountPath: /data
    readOnly: false
  config:
    enabled: true
    mountPath: /config
  downloads:
    enabled: true
    mountPath: /downloads"
  cache:
    enabled: true
    mountPath: /cache
  logs:
    enabled: true
    mountPath: /app/logs